# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.box = "my"
  
  if Vagrant.has_plugin?("vagrant-omnibus")
    config.omnibus.chef_version = 'latest'
  end
config.vm.synced_folder Dir.pwd, "/vagrant", :nfs => false
     config.vm.provision "shell", :inline => "sudo apt-get update -y"
      config.vm.provision "shell", :inline => "sudo apt-get install curl -y"
	     config.vm.provision "shell", :inline => "curl -L https://www.opscode.com/chef/install.sh | sudo bash"


config.vm.provision "chef_solo" do |chef|
#chef.arguments = "chef-license=accept"
chef.channel = "stable"
chef.version = "13"
chef.add_recipe "apache2"
	
	 
  

     
  end

end
