# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.box = "my"
  
  if Vagrant.has_plugin?("vagrant-omnibus")
    config.omnibus.chef_version = 'latest'
  end
   config.vm.network "public_network"

  


   config.vm.provision :chef_solo do |chef|
     chef.cookbooks_path = "recipes/cookbooks"
	 chef.roles_path = "recipes/roles"
	
	 
  

     
  end

end
